# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c93f35bc16a4bb2f9d850d51c8ebd56be6f7f50e6adccca2308eaf96d4a5f3e40a80c54dd407284bfc171a97e9c750653aa985cad167711df6384b147494c91

test:
  secret_key_base: fb031cd6a89d03f3ad48d3ca6de4629fff512f841fafea366fc4af60a4b874a6d8b0435c0a077d996ad46b42072e9201881a8d4043e8eef829fa8ca22143d50c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
